objects:
  can_1:
    type: cylinder
    dimensions:
      height: 0.145
      radius: 0.03
    pose:
      x: 0.8
      y: -0.5
      z: 0.7725
      qw: 1.0
      qx: 0.0
      qy: 0.0
      qz: 0.0
  can_2:
    type: cylinder
    dimensions:
      height: 0.145
      radius: 0.03
    pose:
      x: 0.7
      y: -0.2
      z: 0.7725
      qw: 1.0
      qx: 0.0
      qy: 0.0
      qz: 0.0

# positions on the shelf x: 0.5-1.1, y: 0.50-0.60, z: 0.8 or 1.25
tasks:
  - object: can_1
    gz_link_name: body
    grasp_orientation: horizontal
    place_pose:
      x: 0.9
      y: 0.0
      z: 0.7725
      qw: 1.0
      qx: 0.0
      qy: 0.0
      qz: 0.0
  - object: can_2
    gz_link_name: body
    grasp_orientation: horizontal
    place_pose:
      x: 0.7
      y: -0.2
      z: 0.7725
      qw: 1.0
      qx: 0.0
      qy: 0.0
      qz: 0.0